#!/bin/bash -x
# 
# xmonad startup script. Intended to be run from an xsession configuration
# to run xmonad and some associated programs.
# 
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

#
# GENERAL INITIALIZATION
#

# Identify the home of our gtkrc file, important for setting styles of 
# gtk-based applications
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"



#
# SCREEN CONFIGURATION
#

# We handle our screen configuration using xrandr. You are likely to want to 
# edit this section to match the specific demands of your setup. The below
# setup is for a Lenovo W520 laptop that sometimes has an external monitor
# hooked up via either VGA or DVI, positioned to the left of the laptop.
#
# Note that you can run xrandr at the command line to get a list of your
# connected screens and find out what names you should use to refer to them.

# Activate primary screen 

# If we find that a screen is connected via DVI, activate it and position it
# to the left of the primary screen.
#xrandr | grep 'DP-1 connected' | ifne xrandr --output DP-1 --auto --left-of LVDS-1

# If this is the EPFL desktop, then put DVI to left of DisplayPort
if [ $(hostname) == "desktop" ]; then
   DPI=183
   xrandr | grep 'DP-2 connected' | ifne xrandr --output DP-2 --rotate left
fi

if [ $(hostname) == "jonas-thinkpad" ]; then
   DPI=286
   xrandr | grep 'HDMI-2 connected' | xrandr --dpi 286  --output eDP-1 --auto --left-of HDMI-2 --output HDMI-2 --auto --scale 1.5x1.5 
fi

if [ $(hostname) == "jonas-work-thinkpad" ]; then
   DPI=96
   xrandr | grep 'HDMI-0 connected' | xrandr --dpi $DPI  --output eDP-1-1 --auto --right-of HDMI-0 --output HDMI-0 --auto
fi

# if an argument has been passed in
if [ ! -z $DPI ]; then

    # create a new temporary '.Xresources' file with only the DPI setting
    TMPFILE=$(mktemp)
    echo "! Fonts {{{
         Xft.dpi: $DPI
	 ! These might also be useful depending on your monitor and personal preference:
	 Xft.autohint: 0
	 Xft.lcdfilter:  lcddefault
	 Xft.hintstyle:  hintfull
	 Xft.hinting: 1
	 Xft.antialias: 1
	 Xft.rgba: rgb
    ! }}}" > "$TMPFILE"

    # merge the temporary .Xresources file on top of the already loaded config
    xrdb -merge "$TMPFILE"

    #cleanup
    rm -f "$TMPFILE"
fi
# Load X resources (fixes some font issues)
xrdb -merge ~/.Xresources

# Start compositing to support transparency. You can omit this
# if you prefer not to use any transparency, but it is likely to cause
# ugly black fringing with some programs such as synapse that expect
# transparency support.
#xcompmgr -n &

#
# LOAD SCREEN BACKGROUNDS
#

# To set your backgrounds, run nitrogren /path/to/images
#nitrogen --restore &


#

# Run the gnome-keyring-daemon to avoid issues you otherwise may encounter
# when using gnome applications which expect access to the keyring, such
# as Empathy. This prevents prompts you may otherwise get for invalid
# certificates and the like.
gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh

# Remap caps lock to left control. This is not strictly speaking
# xmonad related, but it's handy if you're a vim user.


# Now, finally, start xmonad
exec xmonad
