#!/bin/bash
# 
# xmonad "startup hook" script. This gets run after xmonad is initialized,
# via the startupHook facility provided by xmonad. It's useful for 
# running any programs which you want to use within xmonad but
# which don't need to be initialized before xmonad is running. 
#
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

#
# TRAY ICON SOFTWARE
#

# Empathy chat client (-h: start hidden, -n: don't connect on launch)
if [ -z "$(pgrep empathy)" ] ; then
    empathy -h -n &
fi

if [ -z "$(pgrep blueman-applet)"] ; then
	if command -v blueman-applet; then
		blueman-applet &
	fi
fi

# Remmina remote desktop connection client (-i: start hidden)
#if [ -z "$(pgrep remmina)" ] ; then
#    remmina -i &
#fi

# Network manager, so we don't have to configure wifi at the command line.
if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet --sm-disable &
fi

# Applet for managing print jobs from the tray.
if [ -z "$(pgrep system-config-printer-applet)" ] ; then
    system-config-printer-applet &
fi

if [ -z "$(pgrep xautolock)" ] ; then
	xautolock -time 10 -locker slock &
fi


#
# APPLICATION LAUNCHER
#

# Use synapse as our app launcher. (-s: don't display until requested) 
if [ -z "$(pgrep synapse)" ] ; then
    synapse -s &
fi

# On login, we unlock the ssh keychain so we're not prompted for 
# passphrases later. We pipe /dev/null to ssh-add to make it realize 
# it's not running in a terminal. Otherwise, it won't launch the prompt.
# 
# If you don't use the ssh keychain you may not want this. Commented
# by default as it is assumed many users will not want this feature.

export SSH_ASKPASS="/usr/bin/ssh-askpass"
cat /dev/null | ssh-add &

# I disable the middle mouse button because otherwise I constantly 
# accidentally paste unwanted text in the middle of my code while scrolling. 
# Note that the id of the mouse device may be different depending on 
# which usb port it is plugged into! To find it, use:
# xinput list |grep 'id='
# In the following command, the id is the first argument, the rest is 
# the remapping.

# Commented by default as it is assumed many users will not want this.
# xinput set-button-map 10 1 0 3 4 5 6 7

# I disabled my touchpad because I hate those things. You can find the id
# of a device you want to disable using "xinput list"; unfortunately it can
# change depending on what devices you have plugged into USB. We extract the
# id of the device from the output of xinput, then use it to disable the
# device
TOUCHPAD_ID=`xinput | grep 'Synaptics TouchPad' | cut -f 2 | cut -f 2 -d =`
#xinput set-prop $TOUCHPAD_ID "Device Enabled" 0
NATURAL_SCROLLING_ID=`xinput list-props | grep 'Natural Scrolling Enabled' | cut -f 2 | cut -f 2 -d =`

# natural scrolling
xinput set-prop $TOUCHPAD_ID $NATURAL_SCROLLING_ID 1


# STARTUP ICON TRAY
#

# We are using stalonetray to create a small icon tray at the
# top right of the screen. You are likely to want to tweak the
# size of the icons and the width of the tray based upon the
# size of your screen and your xmobar configuration. The goal is
# to make stalonetray look like it is part of xmobar.
# 
# Line by line, the options used by default below mean:
# - icons should be aligned with the "East" or right side of the tray
# - the width of the tray should be 5 icons wide by one icon tall, and it 
#   should be located 0 pixels from the right of the screen (-0)() and 0 pixels
#   from the top of the screen (+0).
# - By setting our maximum geometry to the same thing, the tray will not grow.
# - The background color of the tray should be black.
# - This program should not show up in any taskbar.
# - Icons should be set to size "24".
# - Kludges argument of "force_icons_size" forces all icons to really, truly 
#   be the size we set.
# - window-strut "none" means windows are allowed to cover the tray. In
#   other words, trust xmonad to handle this part.
#
# no right monitor as default 

WIDTH_RIGHT_MONITOR=0
if [ $(hostname) == "desktop-epfl" ]; then
	WIDTH_RIGHT_MONITOR=1200
fi

stalonetray \
  --icon-gravity E \
  --geometry 5x1-$WIDTH_RIGHT_MONITOR+0 \
  --max-geometry 6x1-$WIDTH_RIGHT_MONITOR+0 \
  -bg black \
  --skip-taskbar \
  --icon-size 24 \
  --kludges force_icons_size \
  --window-strut none \
&

setxkbmap us  -option 'compose:ralt'
