export GOPATH="/home/data/go"

#if [ -e /usr/share/terminfo/x/xterm+256color ]; then
        export TERM='xterm-256color'
#else
#        export TERM='xterm-color'
#fi
export CDPATH=$GOPATH/src/github.com:$GOPATH/src/code.google.com/p:$GOPATH/src/github.com/epfl-dcsl/
export GEM_HOME=$HOME/local/gems
export PATH="/home/fietz/local/gems/bin/:$PATH"
export PATH="$GOPATH/bin/:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"

gdb-tmux() {
    local id="$(tmux split-pane -hPF "#D" "tail -f /dev/null")"
    tmux last-pane
    local tty="$(tmux display-message -p -t "$id" '#{pane_tty}')"
    gdb -ex "dashboard -output $tty" "$@"
    tmux kill-pane -t "$id"
}

# Powerline
if [ -f `which powerline-daemon` ]; then
  powerline-daemon -q
  POWERLINE_BASH_CONTINUATION=1
  POWERLINE_BASH_SELECT=1
  . /usr/share/powerline/integrations/powerline.sh
fi
